chore: should be the same

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -43,7 +43,7 @@ jobs:
           command: |
             if [ "${CIRCLE_PROJECT_USERNAME}" == "artemv" ]; then
               cp .circleci/.npmrc .
-              (npx semantic-release) || echo "publishing failed"
+              (yarn semantic-release) || echo "publishing failed"
             fi
 
 workflows:
@@ -57,4 +57,4 @@ workflows:
           filters:
             branches:
               only: master
-          context: "my npm-based projects"
+          context: org-global
