fix(ci): try to fix config

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -41,10 +41,12 @@ jobs:
     docker:
       - image: circleci/node:8
     steps:
-      - run: |
-        if [ "${CIRCLE_PROJECT_USERNAME}" == "artemv" ] && [ "${CIRCLE_BRANCH}" == "master" ]; then
-          (npx semantic-release) || echo "publishing failed"
-        fi
+      - run:
+        name: deploy
+        command: |
+          if [ "${CIRCLE_PROJECT_USERNAME}" == "artemv" ] && [ "${CIRCLE_BRANCH}" == "master" ]; then
+            (npx semantic-release) || echo "publishing failed"
+          fi
 
 workflows:
   version: 2
