chore(ci): now with workflow and context vars

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -25,18 +25,34 @@ jobs:
             cp yarn.lock ci-artifacts/
           when: always
 
-      - run:
-          name: test
-          command: yarn test
+  test:
+    docker:
+      - image: circleci/node:8
+      - run: yarn test
       - run:
           name: post-test
           command: |
             node bin/cli.js && mv test-output*.txt ci-artifacts/
       - store_artifacts:
           path: ci-artifacts/
-      - run:
-          name: deploy
-          command: |
-            if [ "${CIRCLE_PROJECT_USERNAME}" == "artemv" ] && [ "${CIRCLE_BRANCH}" == "master" ]; then
-              (npx semantic-release) || echo "publishing failed"
-            fi
+
+  deploy:
+    docker:
+      - image: circleci/node:8
+      - run: |
+        if [ "${CIRCLE_PROJECT_USERNAME}" == "artemv" ] && [ "${CIRCLE_BRANCH}" == "master" ]; then
+          (npx semantic-release) || echo "publishing failed"
+        fi
+
+workflows:
+  version: 2
+  do_everything:
+    jobs:
+      - build
+      - test:
+        requires:
+          - build
+      - deploy:
+        requires:
+          - test
+        context: my npm-based projects
